module.exports = {
    url: 'http://localhost:3000/#/enter',
    elements: {            
        Header: 'input[name="hdrInput"]',
        MKE: 'input[name="mkeInput"]',
        ORI: 'input[name="oriInput"]',
        Name: 'input[name="namInput"]',
        Sex: 'select[name="sexInput"]',
        Sex2: 'option[value="M"]',
        Race: 'select[name="racInput"]',
        Race2: 'option[value="W"]',
        Height: 'input[name="hgtInput"]',
        Weight: 'input[name="wgtInput"]',
        Hair: 'input[name="haiInput"]',
        Offense: 'input[name="offInput"]',
        DateOfWarrant: 'input[name="dowInput"]',
        DriversLicense: 'input[name="olnInput"]',
        DLState: 'input[name="olsInput"]',
        DLDate: 'input[name="oldInput"]',
        LicencePlate: 'input[name="licInput"]',
        LicenseState: 'input[name="lisInput"]',
        LicenceDate: 'input[name="lidInput"]',
        Submit: 'button#saveBtn.button',
        Clear: 'button#clearBtn.button',
        ErrorMsg: 'li[class="errorMessage"]',
        QueryBody: 'span[name="queryBody"]',
        QueryTitle: 'span[name="queryTitle"]',
    }
}